name: ${NAME}

services:
  qemux:
    container_name: ${NAME}
    image: qemux/qemu-docker
    networks:
      qemux:
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    stop_grace_period: 2m
    device_cgroup_rules:
      - 'c *:* rwm'
    environment:
      DISK_SIZE: ${DISK_SIZE}
      RAM_SIZE: ${RAM_SIZE}
      CPU_CORES: ${CPU_CORES}
      DHCP: "Y"
    volumes:
      - "qemux:/storage"
      - "./${ISO}:/boot.iso"

volumes:
  qemux:
    name: ${NAME}

networks:
  qemux:
    name: ${NAME}
