name: qemux

services:
  qemux:
    container_name: qemux
    image: qemux/qemu-docker
    networks:
      - eth
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    stop_grace_period: 2m
    device_cgroup_rules:
      - 'c *:* rwm'
    environment:
      DISK_SIZE: "5G"
      RAM_SIZE: "1G"
      CPU_CORES: "1"
      DHCP: "Y"
    volumes:
      - qemux:/storage
      - ./ubuntu-server.iso:/boot.iso

volumes:
  qemux:
    name: qemux

networks:
  eth:
    name: eth
    driver: macvlan
    driver_opts:
      parent: enp0s25
