name: ${NAME}

services:
  qemux:
    container_name: ${NAME}
    image: qemux/qemu
    restart: always
    networks:
      # qemux:
      #   ipv4_address: 192.168.2.254
      - qemux
    devices:
      - /dev/kvm
      - /dev/net/tun
      #- /dev/vhost-net
      #- /dev/dri
      #- /dev/bus/usb
    cap_add:
      - NET_ADMIN
    ports:
      - ${NOVNC_PORT}:8006
    stop_grace_period: 2m
    device_cgroup_rules:
      - 'c *:* rwm'
    environment:
      DISK_SIZE: ${DISK_SIZE}
      RAM_SIZE: ${RAM_SIZE}
      CPU_CORES: ${CPU_CORES}
      #DHCP: "Y"
      #BOOT: "/boot.img.gz"
      #GPU: "Y"
      #ARGUMENTS: "-device usb-host,vendorid=0x152d,productid=0x0578"
    volumes:
      - "qemux:/storage"
#      - "./${FILENAME}.${FILE_EXT}:/boot.${FILE_EXT}"
#      - "./shared:/shared"

volumes:
  qemux:
    name: ${NAME}

networks:
  qemux:
    name: ${NAME}
  # qemux:
  #   name: ${NAME}
  #   driver: macvlan
  #   driver_opts:
  #     parent: eth0
  #   ipam:
  #     config:
  #       - subnet: 192.168.2.0/24
  #         gateway: 192.168.2.1
